USE [PRD01]
GO

/****** Object:  View [dbo].[TII_BI_WIN_ALERTA_VENTAS]    Script Date: 28/8/2018 15:19:19 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO


CREATE VIEW [dbo].[TII_BI_WIN_ALERTA_VENTAS] AS
select  'CONTABILIZADA'                             ESTADO
    ,   RTRIM(A.CUSTNMBR) + ' - ' +B.CUSTNAME		CLIENTE
	,	B.CUSTNAME									NOMBRE
	,  	A.SOPTYPE									TIPODOCUMENTO
    ,   A.SOPNUMBE									DOCUMENTO 
	,   A.DOCDATE						FECHA
	,	RTRIM( B.SALSTERR)							ZONA
	,   RTRIM( B.USERDEF2)							SEGMENTO
	,	I.USCATVLS_6								DIVISION
	,	RTRIM(LTRIM( B.SLPRSNID ) )					PROVINCIA 
	,   CASE WHEN getdate() BETWEEN Y1.FSTFSCDY AND Y1.LSTFSCDY THEN 'ACTUAL' ELSE 'ANTERIOR' END ANIO
	,	CASE WHEN DATEDIFF(m, Y1.FSTFSCDY, LEFT(CONVERT(CHAR(8), getdate() , 112), 6) + '01')+1 > 12
	                            THEN 12
								ELSE DATEDIFF(m, Y1.FSTFSCDY, LEFT(CONVERT(CHAR(8), getdate() , 112), 6) + '01')+1
								END  CANT_MESES
	,	CASE WHEN A.SOPTYPE = 4 THEN -(C.XTNDPRCE-C.TRDISAMT) 
                                ELSE (C.XTNDPRCE-C.TRDISAMT) END PRECIO
	,   CASE WHEN A.SOPTYPE = 4 THEN -(C.EXTDCOST)
                                ELSE C.EXTDCOST END COSTO
	,   CASE WHEN C.REMPRICE != 0 		
							THEN 
                                 C.REMPRICE-ROUND((C.TRDISAMT/C.QUANTITY)*C.QTYREMAI, 2) 
							ELSE	0   
							END PRECIO_PEND
    ,   CASE WHEN C.REMPRICE != 0  
							THEN ROUND((C.EXTDCOST/C.QUANTITY)*C.QTYREMAI, 2) 
							ELSE 0 	
							END COSTO_PEND
 FROM SOP30200 A 
     INNER JOIN RM00101 B  ON A.CUSTNMBR = B.CUSTNMBR
     INNER JOIN SOP30300 C ON A.SOPTYPE = C.SOPTYPE AND A.SOPNUMBE = C.SOPNUMBE
     INNER JOIN IV00101 I  ON C.ITEMNMBR = I.ITEMNMBR
     INNER JOIN RM00102 E ON A.CUSTNMBR = E.CUSTNMBR AND A.PRSTADCD = E.ADRSCODE
     INNER JOIN RM00301 E1 ON E.SLPRSNID = E1.SLPRSNID 
     INNER JOIN CANADIAN_FISCAL_YEARS Y1 ON A.DOCDATE BETWEEN Y1.FSTFSCDY AND Y1.LSTFSCDY
WHERE A.VOIDSTTS = 0 
  AND A.DOCDATE BETWEEN Y1.FSTFSCDY AND Y1.LSTFSCDY 
  AND A.DOCDATE <= CONVERT(CHAR(8),  getdate() , 112)
  AND I.USCATVLS_6 in('INSTR','ELECT','SICK')
  AND B.SALSTERR in ('W06','W07','W08','W09','W10','WH0')
  AND C.ITEMNMBR not like 'ANTICIPO%'
  AND ( ( A.SOPTYPE = 3 AND  LEFT(A.SOPNUMBE, 2) IN('FV', 'NC', 'ND') 
                                             AND A.SOPNUMBE NOT LIKE 'RX%'  
                                            AND A.SOPNUMBE NOT LIKE 'FV %-T00%' ) OR
        ( A.SOPTYPE != 3 ) )
union  
select  'SIN_COTABILIZAR'
  ,   RTRIM(A.CUSTNMBR) + ' - ' +B.CUSTNAME		CLIENTE
	,	B.CUSTNAME									NOMBRE
	,  	A.SOPTYPE									TIPODOCUMENTO
    ,   A.SOPNUMBE									DOCUMENTO 
	,   A.DOCDATE						FECHA
	,	RTRIM( B.SALSTERR)							ZONA
	,   RTRIM( B.USERDEF2)							SEGMENTO
	,	I.USCATVLS_6								DIVISION
	,	RTRIM(LTRIM( B.SLPRSNID ) )					PROVINCIA 
	,   CASE WHEN getdate() BETWEEN Y1.FSTFSCDY AND Y1.LSTFSCDY THEN 'ACTUAL' ELSE 'ANTERIOR' END ANIO
	,	CASE WHEN DATEDIFF(m, Y1.FSTFSCDY, LEFT(CONVERT(CHAR(8), getdate() , 112), 6) + '01')+1 > 12
	                            THEN 12
								ELSE DATEDIFF(m, Y1.FSTFSCDY, LEFT(CONVERT(CHAR(8), getdate() , 112), 6) + '01')+1
								END  CANT_MESES
	,	CASE WHEN A.SOPTYPE = 4 THEN -(C.XTNDPRCE-C.TRDISAMT) 
                                ELSE (C.XTNDPRCE-C.TRDISAMT) END PRECIO
	,   CASE WHEN A.SOPTYPE = 4 THEN -(C.EXTDCOST)
                                ELSE C.EXTDCOST END COSTO
	,   CASE WHEN C.REMPRICE != 0 		
							THEN 
                                 C.REMPRICE-ROUND((C.TRDISAMT/C.QUANTITY)*C.QTYREMAI, 2) 
							ELSE	0   
							END PRECIO_PEND
    ,   CASE WHEN C.REMPRICE != 0  
							THEN ROUND((C.EXTDCOST/C.QUANTITY)*C.QTYREMAI, 2) 
							ELSE 0 	
							END COSTO_PEND
 FROM SOP10100 A 
     INNER JOIN RM00101 B  ON A.CUSTNMBR = B.CUSTNMBR
     INNER JOIN SOP10200 C ON A.SOPTYPE = C.SOPTYPE AND A.SOPNUMBE = C.SOPNUMBE
     INNER JOIN IV00101 I  ON C.ITEMNMBR = I.ITEMNMBR
     INNER JOIN RM00102 E ON A.CUSTNMBR = E.CUSTNMBR AND A.PRSTADCD = E.ADRSCODE
     INNER JOIN RM00301 E1 ON E.SLPRSNID = E1.SLPRSNID 
     INNER JOIN CANADIAN_FISCAL_YEARS Y1 ON A.DOCDATE BETWEEN Y1.FSTFSCDY AND Y1.LSTFSCDY
WHERE A.VOIDSTTS = 0 
  AND A.DOCDATE BETWEEN Y1.FSTFSCDY AND Y1.LSTFSCDY 
  AND A.DOCDATE <= CONVERT(CHAR(8),  getdate() , 112)
  AND I.USCATVLS_6 in('INSTR','ELECT','SICK')
  AND B.SALSTERR in ('W06','W07','W08','W09','W10','WH0')
  AND C.ITEMNMBR not like 'ANTICIPO%'
  AND A.SOPNUMBE NOT LIKE 'RX%'  
  AND A.VOIDSTTS = 0 
  AND ( ( A.SOPTYPE = 3 AND  LEFT(A.SOPNUMBE, 2) IN('FV', 'NC', 'ND') 
                                             AND A.SOPNUMBE NOT LIKE 'RX%'  
                                            AND A.SOPNUMBE NOT LIKE 'FV %-T00%' ) OR
        ( A.SOPTYPE != 3 ) )



GO


