USE [DYNAMICS]
GO

/****** Object:  StoredProcedure [dbo].[TII_WIN_ART_VEND_X_PROV]    Script Date: 28/8/2018 16:34:19 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE PROCEDURE [dbo].[TII_WIN_ART_VEND_X_PROV]
@FDDE DATETIME, @FHTA datetime, @VENDDDE CHAR(15)
AS
SELECT A.ITEMNMBR, B.ITEMDESC, TRX.QTY CANTIDAD, ISNULL(TRX2.DOCDATE, '19000101') ULTIMO_MOV, ISNULL(D.STOCK, 0) STOCK, 
ISNULL(D.CT_UN_OR, 0) COSTO_UNITARIO, ISNULL(D.COSTO_TOTAL, 0) COSTO_TOTAL
from PRD01..IV00102 A INNER JOIN PRD01..IV00101 B ON A.ITEMNMBR = B.ITEMNMBR
INNER JOIN PRD01..IV00103 C ON A.ITEMNMBR = C.ITEMNMBR AND C.VENDORID = @VENDDDE
LEFT OUTER JOIN PRD01..TII_WIN_INVEN_VAL_MO_WC D ON A.ITEMNMBR = D.ID_ARTICULO
LEFT OUTER JOIN
(SELECT ITEMNMBR, SUM(QUANTITY) QTY FROM PRD01..SOP30300 A INNER JOIN PRD01..SOP30200 B ON A.SOPTYPE = B.SOPTYPE AND A.SOPNUMBE = B.SOPNUMBE
WHERE A.SOPTYPE = 3 AND B.DOCDATE BETWEEN @FDDE AND @FHTA
GROUP BY ITEMNMBR) TRX ON A.ITEMNMBR = TRX.ITEMNMBR
LEFT OUTER JOIN
(SELECT ITEMNMBR, MAX(B.DOCDATE) DOCDATE FROM PRD01..SOP30300 A INNER JOIN PRD01..SOP30200 B ON A.SOPTYPE = B.SOPTYPE AND A.SOPNUMBE = B.SOPNUMBE
WHERE A.SOPTYPE = 3 AND B.DOCDATE NOT BETWEEN @FDDE AND @FHTA
GROUP BY ITEMNMBR) TRX2 ON A.ITEMNMBR = TRX2.ITEMNMBR
WHERE A.LOCNCODE = 'WCENTRAL' 
AND TRX.ITEMNMBR IS NOT NULL 

GO


