USE [PRD01]
GO

/****** Object:  View [dbo].[WIN_TII_DIARIO_RESUMIDO]    Script Date: 28/8/2018 17:03:06 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO




CREATE VIEW [dbo].[WIN_TII_DIARIO_RESUMIDO]
AS
SELECT TOP 100 PERCENT 
GL.ACTNUMST, YEAR(DATEADD(d, -1, DATEADD(m, 1, ASI.MES+'01'))) OPENYEAR,
CONVERT(INT, CONVERT(VARCHAR, ASI.SERIES) + CONVERT(CHAR(8), DATEADD(d, -1, DATEADD(m, 1, ASI.MES+'01')), 112)) JRNENTRY, 0 RCTRXSEQ, '' SOURCDOC,
CASE ASI.SERIES
WHEN -1 THEN 'APERTURA'
WHEN 2 THEN 'RESUMEN CONTABLE'
WHEN 3 THEN 'RESUMEN VENTAS/COBRANZAS'
WHEN 4 THEN 'RESUMEN COMPRAS/PAGOS'
WHEN 5 THEN 'RESUMEN INVENTARIOS'
ELSE 'RESUMEN OTROS' END REFRENCE, '' DSCRIPTN, DATEADD(d, -1, DATEADD(m, 1, ASI.MES+'01')) TRXDATE , '' TRXSORCE, 
GL.ACTINDX, 0 POLLDTRX, '' LASTUSER, CONVERT(datetime, '19000101') LSTDTEDT, '' USWHPSTD, 
CASE ASI.ORGNTSRC
WHEN 'IVADJ' THEN 'AJUSTES'
WHEN 'PORET' THEN 'DEVOLUCIONES COMPRAS'
WHEN 'GLTHS' THEN 'DIARIO GENERAL - HISTORICO'
WHEN 'PMAPY' THEN 'APLICACIONES DE AP'
WHEN 'RMAPY' THEN 'APLICACIONES DE AR'
WHEN 'RMCSH' THEN 'COBRANZAS'
WHEN 'RMMSC' THEN 'ANULACIONES AR'
WHEN 'RMSLS' THEN 'CUENTAS A COBRAR'
WHEN 'CMTRX' THEN 'TRANSACCIONES BANCARIAS'
WHEN 'GLTRX' THEN 'DIARIO GENERAL'
WHEN 'PMPAY' THEN 'PAGOS'
WHEN 'PMVPY' THEN 'ANULACION PAGOS'
WHEN 'PMVVR' THEN 'ANULACION AP'
WHEN 'POIVC' THEN 'ENTRADA FACTURA DE COMPRAS'
WHEN 'RECVG' THEN 'ENTRADA DE RECEPCIONES'
WHEN 'SLSTE' THEN 'TRANSACCIONES DE VENTAS'
WHEN 'IVTFR' THEN 'TRANSFERENCIAS'
WHEN 'PMTRX' THEN 'TRANSACCIONES DE AP'
ELSE 'VARIOS' END ORGNTSRC
, 0 ORGNATYP,
0 QKOFSET, ASI.SERIES, 0 ORTRXTYP, '' ORCTRNUM, '' ORMSTRID, '' ORMSTRNM, '' ORDOCNUM, DATEADD(d, -1, DATEADD(m, 1, ASI.MES+'01')) ORPSTDDT, '' ORTRXSRC,
0 OrigDTASeries, 0 OrigSeqNum, 0 SEQNUMBR, 0 DTA_GL_Status, 0 DTA_Index, 'ARS' CURNCYID, 0 CURRNIDX, '' RATETPID,
0 EXGTBLID, 0 XCHGRATE, DATEADD(d, -1, DATEADD(m, 1, ASI.MES+'01')) EXCHDATE, CONVERT(datetime, '19000101') TIME1, 0 RTCLCMTD, 0 NOTEINDX,
0 ICTRX, '' ORCOMID, 0 ORGINJE, MONTH(DATEADD(d, -1, DATEADD(m, 1, ASI.MES+'01'))) PERIODID, 
CASE WHEN ASI.NETO < 0 THEN ABS(ASI.NETO) ELSE 0 END CRDTAMNT,
CASE WHEN ASI.NETO > 0 THEN ASI.NETO ELSE 0 END DEBITAMT, 
0 ORCRDAMT, 0 ORDBTAMT,
DATEADD(d, -1, DATEADD(m, 1, ASI.MES+'01')) DOCDATE, 0 PSTGNMBR, 0 PPSGNMBR, 0 DENXRATE, 0 MCTRXSTT, '' CorrespondingUnit,
0 DEX_ROW_ID, 0 ORIGEN, '' ACTALIAS, 0 ACCTTYPE, GL2.ACTDESCR, 0 PSTGNTYP, '' ACCATDSC, 'ARS' FUNLCURR, '$' CRNCYSYM, 
2 DECPLCUR, 3 DECSYMBL,
2 THOUSSYM, 'WINTERS ARGENTINA S.A.' CMPNYNAM, 0 DECFUNL, 0 THOUSFUNL, '' FUNLSYM
FROM
(SELECT A.SERIES, A.MES, A.ORGNTSRC, ACTINDX, SUM(DEBITAMT-CRDTAMNT) NETO FROM
(select series, CASE WHEN ORTRXSRC <> ''  THEN LEFT(ORTRXSRC, 5) ELSE LEFT(TRXSORCE, 5) END ORGNTSRC, 
LEFT(CONVERT(CHAR(8), TRXDATE, 112), 6) MES, ACTINDX, DEBITAMT, CRDTAMNT FROM GL30000 
WHERE HSTYEAR = YEAR(TRXDATE)
) A
GROUP BY A.SERIES, A.MES, A.ORGNTSRC, ACTINDX
HAVING SUM(DEBITAMT-CRDTAMNT) <> 0
UNION ALL
SELECT 1 SERIES, A.MES, A.ORGNTSRC, ACTINDX, SUM(DEBITAMT-CRDTAMNT) NETO FROM
(select series, CASE WHEN ORTRXSRC <> ''  THEN LEFT(ORTRXSRC, 5) ELSE LEFT(TRXSORCE, 5) END ORGNTSRC, 
CONVERT(varchar, HSTYEAR) + '01' MES, ACTINDX, DEBITAMT, CRDTAMNT FROM GL30000 
WHERE HSTYEAR <> YEAR(TRXDATE) 
) A
GROUP BY SERIES, MES, ORGNTSRC, ACTINDX
HAVING SUM(DEBITAMT-CRDTAMNT) <> 0	
UNION ALL
SELECT A.SERIES, A.MES, A.ORGNTSRC, ACTINDX, SUM(DEBITAMT-CRDTAMNT) NETO FROM
(select series, CASE WHEN ORTRXSRC <> ''  THEN LEFT(ORTRXSRC, 5) ELSE LEFT(TRXSORCE, 5) END ORGNTSRC, LEFT(CONVERT(CHAR(8), TRXDATE, 112), 6) MES, ACTINDX, DEBITAMT, CRDTAMNT 
FROM GL20000 WHERE OPENYEAR = YEAR(TRXDATE)
) A
GROUP BY SERIES, MES, ORGNTSRC, ACTINDX
HAVING SUM(DEBITAMT-CRDTAMNT) <> 0
UNION ALL
SELECT 1 SERIES, A.MES, A.ORGNTSRC, ACTINDX, SUM(DEBITAMT-CRDTAMNT) NETO FROM
(select series, CASE WHEN ORTRXSRC <> ''  THEN LEFT(ORTRXSRC, 5) ELSE LEFT(TRXSORCE, 5) END ORGNTSRC, 
CONVERT(varchar, OPENYEAR) + '01' MES, ACTINDX, DEBITAMT, CRDTAMNT FROM GL20000 
WHERE OPENYEAR <> YEAR(TRXDATE)
) A
GROUP BY SERIES, MES, ORGNTSRC, ACTINDX
HAVING SUM(DEBITAMT-CRDTAMNT) <> 0
) ASI
INNER JOIN GL00105 GL ON ASI.ACTINDX = GL.ACTINDX
INNER JOIN GL00100 GL2 ON ASI.ACTINDX = GL2.ACTINDX
ORDER BY ASI.MES, ASI.ORGNTSRC, ASI.SERIES, GL.ACTNUMST




GO


