USE [PRD01]
GO

/****** Object:  View [dbo].[WIN_TII_RANKING_VENTAS_ARTICULOS]    Script Date: 28/8/2018 17:03:01 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE VIEW [dbo].[WIN_TII_RANKING_VENTAS_ARTICULOS]
AS
SELECT LEFT(CONVERT(CHAR(8), C.DOCDATE, 112), 6) MESANIO, A.ITEMNMBR, B.ITEMDESC, A.UOFM, A.QUANTITY, A.QUANTITY*A.UNITPRCE - ( (A.QUANTITY*A.UNITPRCE) * (C.TRDISAMT/C.SUBTOTAL)) IMPORTE
FROM SOP30300 A INNER JOIN IV00101 B ON A.ITEMNMBR = B.ITEMNMBR 
INNER JOIN SOP30200 C ON A.SOPTYPE = C.SOPTYPE AND A.SOPNUMBE = C.SOPNUMBE
WHERE A.SOPTYPE = 3 AND C.SUBTOTAL <> 0 AND C.VOIDSTTS = 0 AND A.SOPNUMBE NOT IN(
SELECT DOCNUMBR FROM RM20101 WHERE RMDTYPAL = 1 AND VOIDSTTS = 1
UNION
SELECT DOCNUMBR FROM RM30101 WHERE RMDTYPAL = 1 AND VOIDSTTS= 1)
UNION ALL
SELECT LEFT(CONVERT(CHAR(8), C.DOCDATE, 112), 6) MESANIO, A.ITEMNMBR, B.ITEMDESC, A.UOFM, -A.QUANTITY QUANTITY, - (A.QUANTITY*A.UNITPRCE - ( (A.QUANTITY*A.UNITPRCE) * (C.TRDISAMT/C.SUBTOTAL))) IMPORTE
FROM SOP30300 A INNER JOIN IV00101 B ON A.ITEMNMBR = B.ITEMNMBR 
INNER JOIN SOP30200 C ON A.SOPTYPE = C.SOPTYPE AND A.SOPNUMBE = C.SOPNUMBE
WHERE A.SOPTYPE = 4 AND C.SUBTOTAL <> 0 AND C.VOIDSTTS = 0 AND A.SOPNUMBE NOT IN(
SELECT DOCNUMBR FROM RM20101 WHERE RMDTYPAL = 8 AND VOIDSTTS = 1
UNION
SELECT DOCNUMBR FROM RM30101 WHERE RMDTYPAL = 8 AND VOIDSTTS= 1)
 


GO


