USE [DYNAMICS]
GO

/****** Object:  StoredProcedure [dbo].[WIN_TII_RANKING_VENTAS_ARTICULO_PRC]    Script Date: 28/8/2018 16:28:04 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO


CREATE PROCEDURE [dbo].[WIN_TII_RANKING_VENTAS_ARTICULO_PRC]
@DESDEFECHA datetime, @HASTAFECHA datetime, @VENDORID CHAR(15)
AS

SELECT '1' GRUPO, SUM(A.QUANTITY) QUANTITY, SUM(A.IMPORTE) IMPORTE  INTO #TEMP01
FROM PRD01..WIN_TII_RANKING_VENTAS_ARTICULOS A
INNER JOIN PRD01..IV00103 B ON A.ITEMNMBR = B.ITEMNMBR
WHERE A.MESANIO >= LEFT(CONVERT(CHAR(8), @DESDEFECHA, 112), 6) AND 
A.MESANIO <= LEFT(CONVERT(CHAR(8), @HASTAFECHA, 112), 6)
AND B.VENDORID = @VENDORID

SELECT '1' GRUPO, A.ITEMNMBR, A.ITEMDESC, SUM(A.QUANTITY) QUANTITY, SUM(A.IMPORTE) IMPORTE  INTO #TEMP02
FROM PRD01..WIN_TII_RANKING_VENTAS_ARTICULOS A
INNER JOIN PRD01..IV00103 B ON A.ITEMNMBR = B.ITEMNMBR
WHERE A.MESANIO >= LEFT(CONVERT(CHAR(8), @DESDEFECHA, 112), 6) AND 
A.MESANIO <= LEFT(CONVERT(CHAR(8), @HASTAFECHA, 112), 6)
AND B.VENDORID = @VENDORID
GROUP BY A.ITEMNMBR, A.ITEMDESC

SELECT A.GRUPO, A.ITEMNMBR, A.ITEMDESC, A.QUANTITY, ROUND((A.QUANTITY/B.QUANTITY)*100, 2) PORCCANT, 
A.IMPORTE, ROUND((A.IMPORTE/B.IMPORTE)*100, 2) PORCIMP, 
ISNULL((SELECT VENDNAME FROM PRD01..PM00200 WHERE VENDORID = @VENDORID), '') NOMBRE, ISNULL(C.QTYAVAIL, 0) WCENTRAL,
ISNULL(D.QTYAVAIL, 0) DEPO6
FROM #TEMP02 A INNER JOIN #TEMP01 B ON A.GRUPO = B.GRUPO
LEFT OUTER JOIN (SELECT ITEMNMBR, QTYONHND-ATYALLOC QTYAVAIL FROM PRD01..IV00102 WHERE LOCNCODE = 'WCENTRAL') C ON A.ITEMNMBR = C.ITEMNMBR 
LEFT OUTER JOIN (SELECT ITEMNMBR, QTYONHND-ATYALLOC QTYAVAIL FROM PRD01..IV00102 WHERE LOCNCODE = '6') D ON A.ITEMNMBR = D.ITEMNMBR 




GO


