CREATE VIEW TII_BI_WINLA_FACT_PEDIDO AS
SELECT ESTADO
     , SOPTYPE
     , SOPNUMBE
     , CUSTNMBR
     , CUSTNAME
     , DOCDATE
     , ELECT
     , INST
     , SICK
     , CASE WHEN PRECIO = 0 THEN -100 
            ELSE (1-(COSTO/PRECIO))*100 END RENTAB
     , COSTO 
FROM
(
SELECT A.SOPNUMBE
     , A.SOPTYPE
     , A.CUSTNMBR
     , LEFT(A.CUSTNAME, 20) CUSTNAME
     ,A.DOCDATE DOCDATE
	 ,ESTADO
     , SUM(A.ELECT) [ELECT]
     , SUM(A.INST) [INST]
     , SUM(A.SICK) [SICK]
     , SUM(PRECIO) PRECIO
     , SUM(COSTO) COSTO
FROM 
     ( SELECT 'SIN CONTABILIZAR' ESTADO
	       , A.SOPTYPE
           , A.SOPNUMBE
		    , A.CUSTNMBR
           , LEFT(A.CUSTNAME, 20) CUSTNAME
           , A.DOCDATE DOCDATE
		   ,A.DOCAMNT
           , CASE C.USCATVLS_6
	            WHEN 'COMAT' THEN B.OXTNDPRC-B.ORTDISAM 
	            ELSE 0 END COMAT
	       , CASE WHEN C.USCATVLS_6 LIKE 'ELECT%' 
	            THEN B.OXTNDPRC-B.ORTDISAM 
	            ELSE 0 END ELECT
	       , CASE WHEN C.USCATVLS_6 LIKE 'INST%' 
	            THEN B.OXTNDPRC-B.ORTDISAM 
	            ELSE 0 END INST
	       , CASE C.USCATVLS_6
	            WHEN 'OTROS' THEN B.OXTNDPRC-B.ORTDISAM 
	            ELSE 0 END OTROS
	       , CASE C.USCATVLS_6
	            WHEN 'SICK' THEN B.OXTNDPRC-B.ORTDISAM 
	            ELSE 0 END SICK
	       , B.OXTNDPRC-B.ORTDISAM PRECIO
	       , B.OREXTCST COSTO
      FROM SOP10100 A INNER JOIN SOP10200 B ON A.SOPTYPE = B.SOPTYPE AND A.SOPNUMBE = B.SOPNUMBE
                      INNER JOIN IV00101 C ON B.ITEMNMBR = C.ITEMNMBR
      WHERE 
	  --A.SOPTYPE IN(2) 
      --  AND A.DOCDATE <= CONVERT(CHAR(8), GETDATE(), 112) 
      --  AND DOCDATE > DATEADD(WEEK, -1, GETDATE())
        --AND 
		A.SOPNUMBE NOT LIKE 'RX%'
      UNION ALL
      SELECT 'CONTABILIZADA' ESTADO
	       , A.SOPTYPE
           , A.SOPNUMBE
		    , A.CUSTNMBR
            , LEFT(A.CUSTNAME, 20) CUSTNAME
           ,A.DOCDATE DOCDATE
		   ,A.DOCAMNT
           , CASE C.USCATVLS_6
	            WHEN 'COMAT' THEN B.OXTNDPRC-B.ORTDISAM 
	            ELSE 0 END COMAT
	       , CASE WHEN C.USCATVLS_6 LIKE 'ELECT%' 
	            THEN B.OXTNDPRC-B.ORTDISAM 
	            ELSE 0 END ELECT
	       , CASE WHEN C.USCATVLS_6 LIKE 'INST%' 
	            THEN B.OXTNDPRC-B.ORTDISAM 
	            ELSE 0 END INST
	       , CASE C.USCATVLS_6
	            WHEN 'OTROS' THEN B.OXTNDPRC-B.ORTDISAM 
	            ELSE 0 END OTROS
	       , CASE C.USCATVLS_6
	            WHEN 'SICK' THEN B.OXTNDPRC-B.ORTDISAM 
	            ELSE 0 END SICK
	       , B.OXTNDPRC-B.ORTDISAM PRECIO
	       , B.OREXTCST COSTO
      FROM SOP30200 A INNER JOIN SOP30300 B ON A.SOPTYPE = B.SOPTYPE AND A.SOPNUMBE = B.SOPNUMBE
                      INNER JOIN IV00101 C ON B.ITEMNMBR = C.ITEMNMBR
      WHERE
	  -- A.SOPTYPE IN(2) 
       -- AND A.DOCDATE <= CONVERT(CHAR(8), getdate(), 112) 
       -- AND DOCDATE > DATEADD(WEEK, -1, GETDATE())
       -- AND 
		A.SOPNUMBE NOT LIKE 'RX%'
     )  A 
GROUP BY A.SOPTYPE
            , A.SOPNUMBE
            , A.CUSTNMBR
            , A.DOCAMNT
            , LEFT(A.CUSTNAME, 20)
            , A.DOCDATE
			,A.ESTADO
)  COTIZ