grant select on TII_BI_WIN_ALERTA_COT_PED_SEMANAL to ROL_VISTAS_BI;

grant select on TII_BI_WIN_ALERTA_CTA_CTE to ROL_VISTAS_BI;

grant select on TII_BI_WIN_ALERTA_DIARIA to ROL_VISTAS_BI;

grant select on TII_BI_WIN_ALERTA_VENTA_SEMANAL to ROL_VISTAS_BI;

