USE PRD01
GO

CREATE VIEW TII_BI_WIN_ALERTA_CTA_CTE AS
SELECT	CLI.CUSTNMBR									CLIENTE
		,CLI.CUSTNAME									NOMBRE
		, ISNULL(CC.VENCIDO, 0)							VENCIDO
		, ISNULL(CC.NOVENCIDO, 0)						NOVENCIDO
		, ISNULL(CC.VENCIDO, 0)+ISNULL(CC.NOVENCIDO, 0)	TOTAL
FROM RM00101 CLI 
	LEFT OUTER JOIN
		(SELECT		A.CUSTNMBR
					, B.CUSTNAME
					, SUM(CASE WHEN RMDTYPAL < 7 
								THEN 
									CASE WHEN DUEDATE <= CONVERT(CHAR(8), GETDATE(), 112) 
											THEN CURTRXAM ELSE 0 END 
								ELSE CASE WHEN DOCDATE <= CONVERT(CHAR(8), GETDATE(), 112) 
											THEN -CURTRXAM END 
								END) VENCIDO,
					SUM(CASE WHEN RMDTYPAL < 7 
								THEN CASE WHEN DUEDATE > CONVERT(CHAR(8), GETDATE(), 112) 
										THEN CURTRXAM ELSE 0 END 
								ELSE CASE WHEN DOCDATE > CONVERT(CHAR(8), GETDATE(), 112) 
										THEN -CURTRXAM END 
								END) NOVENCIDO 
			FROM RM20101 A 
					INNER JOIN RM00101 B ON A.CUSTNMBR = B.CUSTNMBR
			WHERE A.VOIDSTTS = 0
			GROUP BY A.CUSTNMBR, B.CUSTNAME	) CC ON CLI.CUSTNMBR = CC.CUSTNMBR
WHERE ISNULL(CC.VENCIDO, 0)+ISNULL(CC.NOVENCIDO, 0) <> 0 

GO