USE [PRD01]
GO

/****** Object:  View [dbo].[TII_BI_WIN_ALERTA_VENTAS]    Script Date: 1/14/2020 11:37:34 AM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

ALTER VIEW [dbo].[TII_BI_WIN_ALERTA_VENTAS]
AS
SELECT	'CONTABILIZADA' ESTADO, 
		A.CUSTNMBR CUSTNMBR, 
		B.CUSTNAME CUSTNAME, 
		A.SOPTYPE SOPTYPE, 
		CASE A.SOPTYPE
				WHEN 1 THEN CASE SUBSTRING(A.SOPNUMBE,1,3)
								WHEN '*CO' THEN '*CO-Anulado)' 
								ELSE RTRIM(SUBSTRING(A.SOPNUMBE,1,3)) + '-Cotización'
								END
				WHEN 2 THEN RTRIM(SUBSTRING(A.SOPNUMBE,1,3)) + '-Pedido'
				WHEN 3 THEN CASE SUBSTRING(A.SOPNUMBE,1,3)
								WHEN 'ND ' THEN RTRIM(SUBSTRING(A.SOPNUMBE,1,3)) + '-Nota de Débito'
								ELSE RTRIM(SUBSTRING(A.SOPNUMBE,1,3)) + '-Factura'
								END
				WHEN 4 THEN CASE SUBSTRING(A.SOPNUMBE,1,3)		
								WHEN 'IND' THEN RTRIM(SUBSTRING(A.SOPNUMBE,1,3)) + '-Interno'
								WHEN 'X00' THEN RTRIM(SUBSTRING(A.SOPNUMBE,1,3)) + '-Remito'
								ELSE RTRIM(SUBSTRING(A.SOPNUMBE,1,3)) + '-Nota de Crédito'
								END
				WHEN 5 THEN RTRIM(SUBSTRING(A.SOPNUMBE,1,3)) + '-Pedido en Espera'
				END TIPO_DOC,
		CASE A.SOPTYPE 
				WHEN 1 THEN 'Cotización'
				WHEN 2 THEN 'Pedido'
				WHEN 3 THEN CASE SUBSTRING(A.SOPNUMBE,1,3) 
								WHEN 'ND ' THEN 'Nota de Débito'
								WHEN 'TKD' THEN 'Nota de Débito'
								ELSE 'Factura'
								END
				WHEN 4 THEN CASE SUBSTRING(A.SOPNUMBE,1,3) 
								WHEN 'IND' THEN 'Otras NC'
								WHEN 'FC ' THEN 'Otras NC'
								WHEN 'X00' THEN 'Otras NC'
								ELSE 'Notas de Crédito'
								END
				WHEN 5 THEN 'Pedido en espera'
				END TIPO_DOC_CONSOLIDADO,
		A.SOPNUMBE SOPNUMBE, 
		A.DOCDATE DOCDATE, 
		RTRIM(B.SALSTERR) ZONA, 
		RTRIM(B.USERDEF2) SEGMENTO, 
		I.USCATVLS_6 DIVISION,
		I.USCATVLS_2 TIPO, 
		'ARGENTINA'              PAIS,
		RTRIM(LTRIM(B.SLPRSNID)) PROVINCIA, 
		CASE WHEN GETDATE() BETWEEN Y1.FSTFSCDY AND Y1.LSTFSCDY 
				THEN 'ACTUAL' 
				ELSE 'ANTERIOR' END ANIO, 
		CASE WHEN DATEDIFF(m, Y1.FSTFSCDY, LEFT(CONVERT(CHAR(8), getdate(), 112), 6) + '01') + 1 > 12 
				THEN 12 
				ELSE DATEDIFF(m, Y1.FSTFSCDY, LEFT(CONVERT(CHAR(8), getdate(), 112), 6) + '01') + 1 END CANT_MESES, 
		CASE WHEN A.SOPTYPE = 4 
				THEN - (C.XTNDPRCE - C.TRDISAMT) 
				ELSE (C.XTNDPRCE - C.TRDISAMT) END PRECIO, 
		CASE WHEN A.SOPTYPE = 4 
				THEN - (C.EXTDCOST) 
                ELSE C.EXTDCOST END COSTO, 
		CASE WHEN C.REMPRICE != 0 
				THEN C.REMPRICE - ROUND((C.TRDISAMT / C.QUANTITY) * C.QTYREMAI, 2) 
				ELSE 0 END PRECIO_PEND, 
        CASE WHEN C.REMPRICE != 0 
				THEN ROUND((C.EXTDCOST / C.QUANTITY) * C.QTYREMAI, 2) 
				ELSE 0 END COSTO_PEND, 
		Y1.FSTFSCDY, 
		Y1.LSTFSCDY, 
		C.LNITMSEQ, 
		C.QUANTITY CANTIDAD
FROM		SOP30200 A 
			INNER JOIN  RM00101 B ON A.CUSTNMBR = B.CUSTNMBR 
			INNER JOIN  SOP30300 C ON A.SOPTYPE = C.SOPTYPE AND A.SOPNUMBE = C.SOPNUMBE 
			INNER JOIN  IV00101 I ON C.ITEMNMBR = I.ITEMNMBR /*		INNER JOIN RM00301 E1 ON E.SLPRSNID = E1.SLPRSNID */ 
			INNER JOIN  CANADIAN_FISCAL_YEARS Y1 ON A.DOCDATE BETWEEN Y1.FSTFSCDY AND Y1.LSTFSCDY
WHERE	A.VOIDSTTS = 0 /* AND A.DOCDATE BETWEEN Y1.FSTFSCDY AND Y1.LSTFSCDY */ 
AND		A.DOCDATE <= CONVERT(CHAR(8), getdate(), 112) /* AND B.SALSTERR IN ('W06','W07','W08','W09','W10','WH0')*/ 
AND		C.ITEMNMBR NOT LIKE 'ANTICIPO%' 
AND		((A.SOPTYPE = 3 AND LEFT(A.SOPNUMBE, 3) IN ('FV', 'NC', 'ND', 'FCE', 'NCE') AND 
		A.SOPNUMBE NOT LIKE 'RX%' AND A.SOPNUMBE NOT LIKE 'FV %-T00%') OR  (A.SOPTYPE != 3))
UNION ALL
SELECT	'SIN_COTABILIZAR', 
		A.CUSTNMBR, 
		B.CUSTNAME, 
		A.SOPTYPE, 
		CASE A.SOPTYPE
				WHEN 1 THEN CASE SUBSTRING(A.SOPNUMBE,1,3)
								WHEN '*CO' THEN '*CO-Anulado)' 
								ELSE RTRIM(SUBSTRING(A.SOPNUMBE,1,3)) + '-Cotización'
								END
				WHEN 2 THEN RTRIM(SUBSTRING(A.SOPNUMBE,1,3)) + '-Pedido'
				WHEN 3 THEN CASE SUBSTRING(A.SOPNUMBE,1,3)
								WHEN 'ND ' THEN RTRIM(SUBSTRING(A.SOPNUMBE,1,3)) + '-Nota de Débito'
								ELSE RTRIM(SUBSTRING(A.SOPNUMBE,1,3)) + '-Factura'
								END
				WHEN 4 THEN CASE SUBSTRING(A.SOPNUMBE,1,3)		
								WHEN 'IND' THEN RTRIM(SUBSTRING(A.SOPNUMBE,1,3)) + '-Interno'
								WHEN 'X00' THEN RTRIM(SUBSTRING(A.SOPNUMBE,1,3)) + '-Remito'
								ELSE RTRIM(SUBSTRING(A.SOPNUMBE,1,3)) + '-Nota de Crédito'
								END
				WHEN 5 THEN RTRIM(SUBSTRING(A.SOPNUMBE,1,3)) + '-Pedido en Espera'
				END TIPO_DOC,
		CASE A.SOPTYPE 
				WHEN 1 THEN 'Cotización'
				WHEN 2 THEN 'Pedido'
				WHEN 3 THEN CASE SUBSTRING(A.SOPNUMBE,1,3) 
								WHEN 'ND ' THEN 'Nota de Débito'
								WHEN 'TKD' THEN 'Nota de Débito'
								ELSE 'Factura'
								END
				WHEN 4 THEN CASE SUBSTRING(A.SOPNUMBE,1,3) 
								WHEN 'IND' THEN 'Otras NC'
								WHEN 'FC ' THEN 'Otras NC'
								WHEN 'X00' THEN 'Otras NC'
								ELSE 'Notas de Crédito'
								END
				WHEN 5 THEN 'Pedido en espera'
				END TIPO_DOC_CONSOLIDADO,
		A.SOPNUMBE, 
		A.DOCDATE, 
		RTRIM(B.SALSTERR), 
		RTRIM(B.USERDEF2), 
		I.USCATVLS_6 DIVISION,
		I.USCATVLS_2 TIPO, 
		'ARGENTINA'              PAIS,
		RTRIM(LTRIM(B.SLPRSNID)), 
		CASE WHEN getdate() BETWEEN Y1.FSTFSCDY AND Y1.LSTFSCDY 
				THEN 'ACTUAL' 
				ELSE 'ANTERIOR' END ANIO, 
		CASE WHEN DATEDIFF(m, Y1.FSTFSCDY, LEFT(CONVERT(CHAR(8),getdate(),112),6) + '01') + 1 > 12 
				THEN 12 
				ELSE DATEDIFF(m, Y1.FSTFSCDY, LEFT(CONVERT(CHAR(8), getdate(), 112), 6) + '01') + 1 END CANT_MESES, 
		CASE WHEN A.SOPTYPE = 4 
				THEN - (C.XTNDPRCE - C.TRDISAMT) 
                ELSE (C.XTNDPRCE - C.TRDISAMT) END PRECIO, 
		CASE WHEN A.SOPTYPE = 4 
				THEN - (C.EXTDCOST) 
				ELSE C.EXTDCOST END COSTO, 
        CASE WHEN C.REMPRICE != 0 
				THEN C.REMPRICE - ROUND((C.TRDISAMT / C.QUANTITY) * C.QTYREMAI, 2) 
				ELSE 0 END PRECIO_PEND, 
		CASE WHEN C.REMPRICE != 0 
				THEN ROUND((C.EXTDCOST / C.QUANTITY) * C.QTYREMAI, 2) 
				ELSE 0 END COSTO_PEND, 
		Y1.FSTFSCDY, 
		Y1.LSTFSCDY, 
		C.LNITMSEQ, 
		C.QUANTITY CANTIDAD
FROM		SOP10100 A 
			INNER JOIN  RM00101 B ON A.CUSTNMBR = B.CUSTNMBR 
			INNER JOIN  SOP10200 C ON A.SOPTYPE = C.SOPTYPE AND A.SOPNUMBE = C.SOPNUMBE 
			INNER JOIN  IV00101 I ON C.ITEMNMBR = I.ITEMNMBR /*   INNER JOIN RM00301 E1 ON E.SLPRSNID = E1.SLPRSNID */ 
			INNER JOIN  CANADIAN_FISCAL_YEARS Y1 ON A.DOCDATE BETWEEN Y1.FSTFSCDY AND Y1.LSTFSCDY
WHERE	A.VOIDSTTS = 0 /* AND A.DOCDATE BETWEEN Y1.FSTFSCDY AND Y1.LSTFSCDY */ 
AND		A.DOCDATE <= CONVERT(CHAR(8), getdate(), 112) /* AND B.SALSTERR in ('W06','W07','W08','W09','W10','WH0')*/ 
AND     C.ITEMNMBR NOT LIKE 'ANTICIPO%' 
AND		A.SOPNUMBE NOT LIKE 'RX%' 
AND		A.VOIDSTTS = 0 
AND		((A.SOPTYPE = 3 AND LEFT(A.SOPNUMBE, 3) IN ('FV', 'NC', 'ND', 'FCE', 'NCE') AND 
		A.SOPNUMBE NOT LIKE 'RX%' AND A.SOPNUMBE NOT LIKE 'FV %-T00%') OR (A.SOPTYPE != 3))

GO


