USE [PRD01]
GO

/****** Object:  View [dbo].[TII_BI_WIN_MAESTRO_CLIENTES]    Script Date: 28/8/2018 15:17:35 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO


CREATE VIEW [dbo].[TII_BI_WIN_MAESTRO_CLIENTES] AS
select CUSTNMBR CLIENTE, CUSTNAME NOMBRE 
FROM RM00101
GO


