USE [PRD02]
GO

/****** Object:  View [dbo].[TII_BI_WINLA_ALERTA_CTA_CTE]    Script Date: 7/16/2019 4:08:29 PM ******/
DROP VIEW [dbo].[TII_BI_WINLA_ALERTA_CTA_CTE]
GO

/****** Object:  View [dbo].[TII_BI_WINLA_ALERTA_CTA_CTE]    Script Date: 7/16/2019 4:08:29 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE VIEW [dbo].[TII_BI_WINLA_ALERTA_CTA_CTE] AS
SELECT	CLI.CUSTNMBR									CLIENTE
		,CLI.CUSTNAME									NOMBRE
		, ISNULL(CC.VENCIDO, 0)							VENCIDO
		, ISNULL(CC.NOVENCIDO, 0)						NOVENCIDO
		, ISNULL(CC.VENCIDO, 0)+ISNULL(CC.NOVENCIDO, 0)	TOTAL
FROM RM00101 CLI 
	LEFT OUTER JOIN
		(SELECT		A.CUSTNMBR
					, B.CUSTNAME
					, SUM(CASE WHEN RMDTYPAL < 7 
								THEN CASE	WHEN DUEDATE <= CONVERT(CHAR(8), GETDATE(), 112) 
											THEN ISNULL(A.ORTRXAMT,A.CURTRXAM) 
											ELSE 0 
											END 
								ELSE CASE WHEN DOCDATE <= CONVERT(CHAR(8), GETDATE(), 112) 
											THEN -ISNULL(A.ORTRXAMT,A.CURTRXAM)  END 
								END) VENCIDO,
					SUM(CASE WHEN RMDTYPAL < 7 
								THEN CASE	WHEN DUEDATE > CONVERT(CHAR(8), GETDATE(), 112) 
											THEN ISNULL(A.ORTRXAMT,A.CURTRXAM) 
											ELSE 0 
											END 
								ELSE CASE	WHEN DOCDATE > CONVERT(CHAR(8), GETDATE(), 112) 
											THEN -ISNULL(A.ORTRXAMT,A.CURTRXAM)  
											END 
								END) NOVENCIDO 
			FROM	RM20101 A 
					INNER JOIN RM00101 B ON A.CUSTNMBR = B.CUSTNMBR
			WHERE A.VOIDSTTS = 0
			--AND CONVERT(CHAR(8),A.DOCDATE ,112) >= 20180401
			GROUP BY A.CUSTNMBR, B.CUSTNAME	) CC ON CLI.CUSTNMBR = CC.CUSTNMBR
WHERE ISNULL(CC.VENCIDO, 0)+ISNULL(CC.NOVENCIDO, 0) <> 0 






GO


