CREATE VIEW TII_BI_WINLA_CTA_CTE AS
SELECT CONVERT(CHAR(15), CLI.CUSTNMBR) CLIENTE
, convert(CHAR(64), CLI.CUSTNAME) NOMBRE
, ISNULL(CC.VENCIDO, 0) VENCIDO
,  ISNULL(CC.NOVENCIDO, 0) NOVENCIDO
,  ISNULL(CC.VENCIDO, 0)+ISNULL(CC.NOVENCIDO, 0) TOTAL
, ISNULL(CC.VENCIDO, 0)+ISNULL(CC.NOVENCIDO, 0) TOTALNUM
FROM RM00101 CLI LEFT OUTER JOIN
(SELECT A.CUSTNMBR
  , B.CUSTNAME, 
SUM(CASE WHEN A.RMDTYPAL < 7 THEN CASE WHEN DUEDATE <= CONVERT(CHAR(8), GETDATE(), 112) 
   THEN ISNULL(C.ORCTRXAM,A.CURTRXAM) ELSE 0 END ELSE CASE WHEN A.DOCDATE <= CONVERT(CHAR(8), GETDATE(), 112) THEN -ISNULL(C.ORCTRXAM,A.CURTRXAM) END END) VENCIDO,
SUM(CASE WHEN A.RMDTYPAL < 7 THEN CASE WHEN DUEDATE > CONVERT(CHAR(8), GETDATE(), 112) THEN ISNULL(C.ORCTRXAM,A.CURTRXAM) ELSE 0 END ELSE CASE WHEN A.DOCDATE > CONVERT(CHAR(8), GETDATE(), 112) THEN -ISNULL(C.ORCTRXAM,A.CURTRXAM) END END) NOVENCIDO 
FROM RM20101 A INNER JOIN RM00101 B ON A.CUSTNMBR = B.CUSTNMBR
       LEFT OUTER JOIN MC020102 C ON A.RMDTYPAL = C.RMDTYPAL AND A.DOCNUMBR = C.DOCNUMBR
WHERE A.VOIDSTTS = 0
GROUP BY A.CUSTNMBR, B.CUSTNAME	) CC ON CLI.CUSTNMBR = CC.CUSTNMBR
WHERE ISNULL(CC.VENCIDO, 0)+ISNULL(CC.NOVENCIDO, 0) <> 0 