USE [PRD02]
GO

/****** Object:  View [dbo].[TII_BI_WINLA_ALERTA_VENTAS]    Script Date: 7/16/2019 4:11:23 PM ******/
DROP VIEW [dbo].[TII_BI_WINLA_ALERTA_VENTAS]
GO

/****** Object:  View [dbo].[TII_BI_WINLA_ALERTA_VENTAS]    Script Date: 7/16/2019 4:11:23 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO


CREATE VIEW [dbo].[TII_BI_WINLA_ALERTA_VENTAS]
AS
SELECT  'CONTABILIZADA' ESTADO
		, A.CUSTNMBR CUSTNMBR
		, B.CUSTNAME CUSTNAME
		, A.SOPTYPE SOPTYPE
		, A.SOPNUMBE SOPNUMBE, 
		A.DOCDATE DOCDATE
		, RTRIM(B.SALSTERR) ZONA,
		 RTRIM(B.USERDEF2) SEGMENTO
		 , I.USCATVLS_6 TIPO
		 , RTRIM(LTRIM(B.SLPRSNID)) PROVINCIA
		 , CASE WHEN GETDATE() BETWEEN Y1.FSTFSCDY AND Y1.LSTFSCDY 
					THEN 'ACTUAL' 
					ELSE 'ANTERIOR' END ANIO
		,  CASE WHEN DATEDIFF(m, Y1.FSTFSCDY, LEFT(CONVERT(CHAR(8), getdate(), 112), 6) + '01') + 1 > 12 
					THEN 12 
					ELSE DATEDIFF(m, Y1.FSTFSCDY, LEFT(CONVERT(CHAR(8), getdate(), 112), 6) + '01')  + 1 
					END CANT_MESES
		, CASE WHEN A.SOPTYPE = 4 
					THEN - (C.OXTNDPRC - C.ORTDISAM) 
					ELSE (C.OXTNDPRC - C.ORTDISAM) 
					END PRECIO
		, CASE WHEN A.SOPTYPE = 4 
					THEN - (C.OREXTCST) 
                    ELSE C.OREXTCST 
					END COSTO
		, CASE WHEN C.OREPRICE != 0 
					THEN C.OREPRICE - ROUND((C.ORTDISAM / C.QUANTITY) * C.QTYREMAI, 2) 
					ELSE 0 
					END PRECIO_PEND
		, CASE WHEN C.OREPRICE != 0 
					THEN ROUND((C.OREXTCST / C.QUANTITY) * C.QTYREMAI, 2) 
					ELSE 0 
					END COSTO_PEND
		, Y1.FSTFSCDY
		, Y1.LSTFSCDY
		, C.LNITMSEQ
		, C.QUANTITY CANTIDAD
FROM            SOP30200 A 
				INNER JOIN RM00101 B ON A.CUSTNMBR = B.CUSTNMBR 
				INNER JOIN SOP30300 C ON A.SOPTYPE = C.SOPTYPE AND A.SOPNUMBE = C.SOPNUMBE 
				INNER JOIN  IV00101 I ON C.ITEMNMBR = I.ITEMNMBR /*		INNER JOIN RM00301 E1 ON E.SLPRSNID = E1.SLPRSNID */ 
				INNER JOIN CANADIAN_FISCAL_YEARS Y1 ON A.DOCDATE BETWEEN Y1.FSTFSCDY AND Y1.LSTFSCDY
WHERE        A.VOIDSTTS = 0 /* AND A.DOCDATE BETWEEN Y1.FSTFSCDY AND Y1.LSTFSCDY */ 
		AND A.DOCDATE <= CONVERT(CHAR(8), getdate(), 112) /* AND B.SALSTERR IN ('W00','W05','W10','W15','W20','W30')*/ 
		AND C.ITEMNMBR NOT LIKE 'ANTICIPO%' 
		AND ((A.SOPTYPE = 3 
		AND LEFT(A.SOPNUMBE, 3) IN ('TKT', 'TKC', 'TKD') 
		AND A.SOPNUMBE NOT LIKE 'RX%' 
		AND A.SOPNUMBE NOT LIKE 'FV %-T00%') OR (A.SOPTYPE != 3))
		AND CONVERT(CHAR(8),A.DOCDATE ,112) >= 20180401

UNION ALL
SELECT        'SIN_COTABILIZAR'
		, A.CUSTNMBR
		, B.CUSTNAME
		, A.SOPTYPE
		, A.SOPNUMBE
		, A.DOCDATE
		, RTRIM(B.SALSTERR)
		, RTRIM(B.USERDEF2)
		, I.USCATVLS_6
		, RTRIM(LTRIM(B.SLPRSNID))
		, CASE WHEN getdate() BETWEEN Y1.FSTFSCDY AND Y1.LSTFSCDY 
				THEN 'ACTUAL' 
				ELSE 'ANTERIOR' 
				END ANIO
		, CASE WHEN DATEDIFF(m, Y1.FSTFSCDY, LEFT(CONVERT(CHAR(8), getdate(), 112), 6) + '01') + 1 > 12 
				THEN 12 
				ELSE DATEDIFF(m, Y1.FSTFSCDY, LEFT(CONVERT(CHAR(8), getdate(), 112), 6) + '01') + 1 
				END CANT_MESES
		, CASE WHEN A.SOPTYPE = 4 
				THEN - (C.OXTNDPRC - C.ORTDISAM) 
                ELSE (C.OXTNDPRC - C.ORTDISAM) 
				END PRECIO
		, CASE WHEN A.SOPTYPE = 4 
				THEN - (C.OREXTCST) 
				ELSE C.OREXTCST 
				END COSTO
		, CASE WHEN C.OREPRICE != 0 
				THEN C.OREPRICE - ROUND((C.ORTDISAM / C.QUANTITY) * C.QTYREMAI, 2) 
				ELSE 0 
				END PRECIO_PEND
		, CASE WHEN C.OREPRICE != 0 
				THEN ROUND((C.OREXTCST / C.QUANTITY)   * C.QTYREMAI, 2) 
				ELSE 0
				END COSTO_PEND
		, Y1.FSTFSCDY
		, Y1.LSTFSCDY
		, C.LNITMSEQ
		, C.QUANTITY CANTIDAD
FROM            SOP10100 A INNER JOIN
                RM00101 B ON A.CUSTNMBR = B.CUSTNMBR 
				INNER JOIN SOP10200 C ON A.SOPTYPE = C.SOPTYPE AND A.SOPNUMBE = C.SOPNUMBE 
				INNER JOIN IV00101 I ON C.ITEMNMBR = I.ITEMNMBR /*   INNER JOIN RM00301 E1 ON E.SLPRSNID = E1.SLPRSNID */ 
				INNER JOIN CANADIAN_FISCAL_YEARS Y1 ON A.DOCDATE BETWEEN Y1.FSTFSCDY AND Y1.LSTFSCDY
WHERE        A.VOIDSTTS = 0 /* AND A.DOCDATE BETWEEN Y1.FSTFSCDY AND Y1.LSTFSCDY */ 
AND A.DOCDATE <= CONVERT(CHAR(8), getdate(), 112) /* AND B.SALSTERR in ('W00','W05','W10','W15','W20','W30')*/ 
AND C.ITEMNMBR NOT LIKE 'ANTICIPO%' 
AND A.SOPNUMBE NOT LIKE 'RX%' 
AND A.VOIDSTTS = 0 
AND ((A.SOPTYPE = 3 
AND LEFT(A.SOPNUMBE, 3) IN ('TKT', 'TKC', 'TKD') 
AND A.SOPNUMBE NOT LIKE 'RX%' 
AND A.SOPNUMBE NOT LIKE 'FV %-T00%') OR  (A.SOPTYPE != 3))
AND CONVERT(CHAR(8),A.DOCDATE ,112) >= 20180401


GO




