USE [PRD02]
GO

/****** Object:  View [dbo].[TII_BI_WINLA_MAESTRO_CLIENTES]    Script Date: 7/16/2019 4:12:31 PM ******/
DROP VIEW [dbo].[TII_BI_WINLA_MAESTRO_CLIENTES]
GO

/****** Object:  View [dbo].[TII_BI_WINLA_MAESTRO_CLIENTES]    Script Date: 7/16/2019 4:12:31 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE VIEW [dbo].[TII_BI_WINLA_MAESTRO_CLIENTES]
AS
SELECT CUSTNMBR, CUSTNAME, CUSTCLAS, ADDRESS1, ADDRESS2, ADDRESS3, COUNTRY, CITY, STATE, ZIP, USERDEF2, TXRGNNUM, SALSTERR
FROM RM00101

GO


