USE [PRD02]
GO

/****** Object:  View [dbo].[TII_BI_WINLA_MAESTRO_SEGMENTOS]    Script Date: 7/16/2019 4:13:27 PM ******/
DROP VIEW [dbo].[TII_BI_WINLA_MAESTRO_SEGMENTOS]
GO

/****** Object:  View [dbo].[TII_BI_WINLA_MAESTRO_SEGMENTOS]    Script Date: 7/16/2019 4:13:27 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE VIEW [dbo].[TII_BI_WINLA_MAESTRO_SEGMENTOS]
AS
SELECT        'D.COMERCIALES' COD_SEGMENTO, '' NOMBRE_SEGMENTO
UNION
SELECT        'D.INDUSTRIALES', ''
UNION
SELECT        'OEM', ''
UNION
SELECT        'PROYECTOS', ''
UNION
SELECT        'KAM', ''
UNION
SELECT        'EX CLIENTE', ''

GO




