USE [PRD02]
GO

/****** Object:  View [dbo].[TII_BI_WINLA_MAESTRO_SEGMENTOS]    Script Date: 1/14/2020 12:29:42 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

ALTER VIEW [dbo].[TII_BI_WINLA_MAESTRO_SEGMENTOS]
AS
SELECT         'D.COMERCIALES' COD_SEGMENTO, 'D.COMERCIALES' NOMBRE_SEGMENTO
UNION
SELECT        'D.INDUSTRIALES', 'D.INDUSTRIALES'
UNION
SELECT        'OEM', 'OEM'
UNION
SELECT        'PROYECTOS', 'PROYECTOS'
UNION
SELECT        'KAM', 'KAM'
UNION
SELECT        'EX CLIENTE', 'EX CLIENTE'

GO


