USE [PRD02]
GO

/****** Object:  View [dbo].[TII_BI_WINLA_MAESTRO_ZONAS]    Script Date: 7/16/2019 4:14:14 PM ******/
DROP VIEW [dbo].[TII_BI_WINLA_MAESTRO_ZONAS]
GO

/****** Object:  View [dbo].[TII_BI_WINLA_MAESTRO_ZONAS]    Script Date: 7/16/2019 4:14:14 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE VIEW [dbo].[TII_BI_WINLA_MAESTRO_ZONAS]
AS
SELECT        SALSTERR, SLTERDSC, INACTIVE, SLPRSNID, STMGRFNM, STMGRMNM, STMGRLNM, COUNTRY, COSTTODT, TTLCOMTD, TTLCOMLY, NCOMSLYR, COMSLLYR, CSTLSTYR, COMSLTDT, NCOMSLTD, 
                         KPCALHST, KPERHIST, NOTEINDX, MODIFDT, CREATDDT, DEX_ROW_TS, DEX_ROW_ID
FROM            dbo.RM00303
WHERE        (SALSTERR IN ('W00', 'W05', 'W10', 'W15', 'W20'))

GO



