grant select on TII_BI_WINLA_CTA_CTE to ROL_VISTAS_BI;

grant select on TII_BI_WINLA_ALERTA_CTA_CTE_PROV to ROL_VISTAS_BI;
grant select on TII_BI_WINLA_ALERTA_VENTAS to ROL_VISTAS_BI;
grant select on TII_BI_WINLA_MAESTRO_CLIENTES to ROL_VISTAS_BI;
grant select on TII_BI_WINLA_MAESTRO_PROVINCIAS to ROL_VISTAS_BI;
grant select on TII_BI_WINLA_MAESTRO_SEGMENTOS to ROL_VISTAS_BI;
grant select on TII_BI_WINLA_MAESTRO_ZONAS to ROL_VISTAS_BI;

